### ISSUE TITLE
ERROR in error TS1149: File name /src/app/modules/layout/Footer/footer.component.ts' differs from already included file name 

### ISSUE THREAD

**Issue by rahulsalve1919** [ramsatt/Angular8AdminLteBasicTeplate#2]
It's not working 
  
When I am trying  to run using ng build on mac but getting below error :

ERROR in error TS1149: File name '/Users/rahul/Documents/Angular8/Angular8AdminLteBasicTeplate/src/app/modules/layout/Footer/footer.component.ts' differs from already included file name '/Users/rahul/Documents/Angular8/Angular8AdminLteBasicTeplate/src/app/modules/layout/footer/footer.component.ts' only in casing.

so I have tried by adding "forceConsistentCasingInFileNames": false in tsconfig.json file.

Could @ramsatt  please help me to resolve this?

**Comment by rahulsalve1919** [comment]
Issue fixed.

For that, I changed the folder name from 'Footer' to 'footer'.

**Comment by ramsatt** [comment]
Great...
